# Buildpack API version
api = "0.10"

# Extension ID and metadata
[extension]
id = "tech.monstrs.extensions.graphicsmagick"
version = "0.0.1"
name = "GraphicsMagick Extension"
homepage = "https://github.com/monstrs/buildpacks/tree/master/extensions/graphicsmagick"
description = "Installs GraphicsMagick on the runtime base image"