api = "0.6"

[buildpack]
id = "tech.monstrs.buildpacks.yarn-workspace"
version = "0.0.3"
name = "Yarn Workspace Buildpack"

[metadata]
include_files = ["buildpack.toml"]

[[order]]

[[order.group]]
id = "tech.monstrs.buildpacks.yarn-install"
version = "0.0.3"

[[order.group]]
id = "tech.monstrs.buildpacks.yarn-cache"
version = "0.0.3"

[[order.group]]
id = "tech.monstrs.buildpacks.yarn-workspace-start"
version = "0.0.3"
